In [ ]:
import pandas as pd

In [ ]:

# cleaning data
df = pd.read_csv("/content/ncvoter60.csv", sep="\t", encoding="ISO-8859-1")

/tmp/ipykernel_1076/363420199.py:3: DtypeWarning: Columns (17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/ncvoter60.csv", sep="\t", encoding="ISO-8859-1")

In [ ]:
df.head()

,county_id,county_desc,voter_reg_num,ncid,last_name,first_name,middle_name,name_suffix_lbl,status_cd,voter_status_desc,...,sanit_dist_abbrv,sanit_dist_desc,rescue_dist_abbrv,rescue_dist_desc,munic_dist_abbrv,munic_dist_desc,dist_1_abbrv,dist_1_desc,vtd_abbrv,vtd_desc
0,60,MECKLENBURG,1000747554,CW1441960,A,CARMEN,VENUS,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,138.0,138.0
1,60,MECKLENBURG,1000374126,CW1170669,A,CHUA,NaN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,230.0,230.0
2,60,MECKLENBURG,1000363600,CW1164524,A,HAI,NaN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,228.0,228.0
3,60,MECKLENBURG,1000166591,CW1016763,A,HUOI,NaN,NaN,I,INACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,230.0,230.0
4,60,MECKLENBURG,1000368416,CW1167483,A,LAI,NaN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,228.0,228.0

In [ ]:
df.shape

(974925, 70)

In [ ]:
# checking if decoded correctly
df[df["last_name"]=="O'HARA"]

,county_id,county_desc,voter_reg_num,ncid,last_name,first_name,middle_name,name_suffix_lbl,status_cd,voter_status_desc,...,sanit_dist_abbrv,sanit_dist_desc,rescue_dist_abbrv,rescue_dist_desc,munic_dist_abbrv,munic_dist_desc,dist_1_abbrv,dist_1_desc,vtd_abbrv,vtd_desc
646959,60,MECKLENBURG,1000772775,CW1458981,O'HARA,AIDAN,R,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,141.0,141.0
646960,60,MECKLENBURG,1000300341,CW1119576,O'HARA,ANITA,NaN,NaN,I,INACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,121.0,121.0
646961,60,MECKLENBURG,1123626,CW475587,O'HARA,CAITILIN,NaN,NaN,R,REMOVED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646962,60,MECKLENBURG,1000692448,CW1399588,O'HARA,CAROL,ANN,NaN,I,INACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,137.0,137.0
646963,60,MECKLENBURG,1000095726,CW961286,O'HARA,CHARLES,ROBERT,III,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,87.0,87.0
646964,60,MECKLENBURG,1000496844,CW1119577,O'HARA,DARCY,MAY,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,2.0,2.0
646965,60,MECKLENBURG,1000465660,CW1241036,O'HARA,DENNIS,BENJAMIN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,12.0,12.0
646966,60,MECKLENBURG,996006,CW358008,O'HARA,GEORGE,ALEXANDER,III,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,238.1,238.1
646967,60,MECKLENBURG,1000389584,CW1181404,O'HARA,GRAIG,THOMAS,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,HUN,HUNTERSVILLE,26.0,PROSECUTORIAL DISTRICT 26,142.0,142.0
646968,60,MECKLENBURG,223500,CW56716,O'HARA,IONE,SHEPPARD,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,DAV,DAVIDSON,26.0,PROSECUTORIAL DISTRICT 26,206.0,206.0
646969,60,MECKLENBURG,978345,CW343174,O'HARA,JOHN,JOSEPH,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,MAT,MATTHEWS,26.0,PROSECUTORIAL DISTRICT 26,215.0,215.0
646970,60,MECKLENBURG,1000565120,CW1313946,O'HARA,JOHN,EDWARD,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,UNI,UNINCORPORATED,26.0,PROSECUTORIAL DISTRICT 26,212.0,212.0
646971,60,MECKLENBURG,1000342057,BN403749,O'HARA,JONATHAN,BENNETT,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,223.1,223.1
646972,60,MECKLENBURG,1000525162,CW1283173,O'HARA,KATLIN,ANN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,HUN,HUNTERSVILLE,26.0,PROSECUTORIAL DISTRICT 26,209.0,209.0
646973,60,MECKLENBURG,1000796106,CW1477515,O'HARA,KAYLEIGH,GRACE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,137.0,137.0
646974,60,MECKLENBURG,1000310639,CW1127237,O'HARA,LIAM,FRANCIS,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,61.0,61.0
646975,60,MECKLENBURG,662461,CW194504,O'HARA,LOU,W,NaN,R,REMOVED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646976,60,MECKLENBURG,1000323173,EL80629,O'HARA,LYNDLY,ALEXANDRA,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,61.0,61.0
646977,60,MECKLENBURG,999839355,CW744113,O'HARA,MEGAN,CHRISTINE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,223.1,223.1
646978,60,MECKLENBURG,1300658,CW636632,O'HARA,MELISSA,RENEE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,87.0,87.0
646979,60,MECKLENBURG,1021445,CW380254,O'HARA,MICHAEL,PATRICK,SR,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,128.0,128.0
646980,60,MECKLENBURG,918691,CW294353,O'HARA,MICHAEL,BATTLE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,100.0,100.0
646981,60,MECKLENBURG,1000389576,CW1181397,O'HARA,MIKAYLA,SUSAN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,HUN,HUNTERSVILLE,26.0,PROSECUTORIAL DISTRICT 26,142.0,142.0
646982,60,MECKLENBURG,1000416919,CW1202765,O'HARA,NICOLE,SAFFRON,NaN,I,INACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,137.0,137.0
646983,60,MECKLENBURG,956829,CW325330,O'HARA,PATRICIA,M,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,128.0,128.0
646984,60,MECKLENBURG,744365,CW231828,O'HARA,PATRICK,G,NaN,R,REMOVED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646985,60,MECKLENBURG,99873267,CW716656,O'HARA,STACY,KAYE,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,243.0,243.0
646986,60,MECKLENBURG,1000692449,CW1399589,O'HARA,TIMOTHY,PATRICK,NaN,I,INACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,137.0,137.0
646987,60,MECKLENBURG,626000,CW182106,O'HARA,TRACIE,E,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,46.0,46.0
646988,60,MECKLENBURG,999906380,CW801489,O'HARA,TRAVIS,JOHN,NaN,A,ACTIVE,...,NaN,NaN,NaN,NaN,CLT,CHARLOTTE,26.0,PROSECUTORIAL DISTRICT 26,37.0,37.0

In [ ]:
# remove "removed"/"denied" voter desc
df = df[df['voter_status_desc'].isin(['ACTIVE', 'INACTIVE'])]
print(df.shape)

(839608, 70)

In [ ]:
df['precinct_abbrv'].isna().sum()
df = df.dropna(subset=["precinct_abbrv"])
print(df.shape)

(839541, 70)

In [ ]:
# Columns we need to keep
columns_to_keep = [
    # Names
    "last_name",
    "first_name",
    "middle_name",
    # Address
    "res_street_address",
    "res_city_desc",
    "precinct_abbrv",
    # Demographics
    "race_code",
    "ethnic_code",
    "party_cd",
    "gender_code",
    "birth_year",
    "age_at_year_end",
]

df = df[columns_to_keep].copy()
print(df.shape)
df.head(6)

(839541, 12)

,last_name,first_name,middle_name,res_street_address,res_city_desc,precinct_abbrv,race_code,ethnic_code,party_cd,gender_code,birth_year,age_at_year_end
0,A,CARMEN,VENUS,2405 WOODEN PEG CT,CHARLOTTE,138.0,A,NL,UNA,F,2003,23
1,A,CHUA,NaN,10627 ELM BEND DR,CHARLOTTE,230.0,A,NL,DEM,M,1993,33
2,A,HAI,NaN,1927 O'HARA DR,CHARLOTTE,228.0,A,NL,UNA,M,1983,43
3,A,HUOI,NaN,14331 WILLIAMS GLENN RD,CHARLOTTE,230.0,A,NL,DEM,M,1982,44
4,A,LAI,NaN,12321 CHARING GROVE LN,CHARLOTTE,228.0,A,NL,REP,M,1984,42
5,A,LAM,NaN,12321 CHARING GROVE LN,CHARLOTTE,228.0,U,UN,REP,U,1988,38

In [ ]:
df[df.columns].isna().sum()

last_name                13
first_name               11
middle_name           93197
res_street_address        0
res_city_desc            26
precinct_abbrv            0
race_code                 0
ethnic_code               0
party_cd                  0
gender_code               0
birth_year                0
age_at_year_end           0
dtype: int64

In [ ]:
# drop fn/ln nas
df = df.dropna(subset=["last_name", "first_name", "res_city_desc"])
print(df.shape)

(839491, 12)

In [ ]:
pres = df.groupby("precinct_abbrv").size()
pres.sort_values().head(10)

precinct_abbrv
64.0     1346
59.0     1405
129.0    1459
125.0    1463
110.0    1532
97.0     1576
65.0     1587
68.0     1597
67.0     1671
5.0      1715
dtype: int64

In [ ]:
# shuffle zip entries
pres = pres.sample(frac=1.0, random_state=42)
print(pres.cumsum())

precinct_abbrv
139.1      4087
17.0       6529
204.1     12446
97.0      14022
69.0      18914
          ...
107.1    823950
15.0     828715
93.0     830772
228.0    835841
103.0    839491
Length: 195, dtype: int64

In [ ]:
shifted = pres.cumsum().shift(1)
condition = (shifted < 10000) | (shifted.isna())
pres[condition]

precinct_abbrv
139.1    4087
17.0     2442
204.1    5917
dtype: int64

In [ ]:
idx = pres[condition].index
df_scoped = df[df["precinct_abbrv"].isin(idx)]
print(df_scoped.shape)

(12446, 12)

In [ ]:
df_scoped["precinct_abbrv"].unique()

array([204.1,  17. , 139.1])

In [ ]:
df["res_street_address"] = df["res_street_address"].str.strip()

In [ ]:
df_scoped.to_csv("ncvoter_final.csv", index=False)